[package]
name = "Zookeeper"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros", "time", "sync"] }
rand = "0.9.0-alpha.2"
futures = "0.3.31"
